name: "Bug反馈"
description: "报告插件中遇到的错误以帮助我们改进"
labels: [bug, 新提交]
body:
- type: checkboxes
  id: "check-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 Issues 页面中搜索，确认了这一 Bug 未被提交过。"
      required: true
- type: textarea
  id: "desc"
  attributes:
    label: 描述
    description: "详细描述该 Bug 的具体表现。"
  validations:
    required: true
- type: textarea
  id: "repro"
  attributes:
    label: 重现步骤
    description: "详细描述要怎么操作才能再次触发这个 Bug。"
    value: |
      1. 点击xxxx
      2. 往下滚，然后点击xxxx
  validations:
    required: true
- type: textarea
  id: "logs"
  attributes:
    label: 日志与附件
    description: "上传日志文件或相关截图。"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: false