name: "功能建议"
description: "为项目提出新功能或改进建议"
labels: [功能建议, 新提交]
body:
- type: checkboxes
  id: "check-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已在 Issues 页面中搜索，确认了这一提案未被提交过。"
      required: true
    - label: "我已查看功能投票页面，确认了这一提案未在投票列表中。"
      required: true
- type: textarea
  id: "desc"
  attributes:
    label: 描述
    description: "详细描述你想添加的功能具体是怎样的。"
  validations:
    required: true 