name: Build and Release

on:
  push:
    paths-ignore:
        - "documentation/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
        contents: write
    name: Build and Release
    runs-on: ubuntu-latest
    outputs:
        MATCHZY_VERSION: ${{ steps.MENGZY_VERSION.outputs.MATCHZY_VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Get MEngZy Version
        id: MENGZY_VERSION
        run: |
            MATCHZY_VERSION=$(grep -oP 'ModuleVersion\s*=>\s*"\K[^"]*' MatchZy.cs)
            echo "MATCHZY_VERSION=$MATCHZY_VERSION" >> $GITHUB_ENV

      - name: Build and Release Artifacts
        run: |
          CSSHARP_VERSION=$(grep -Po '<PackageReference Include="CounterStrikeSharp.API" Version="\K\d+(\.\d+)*' MatchZy.csproj | sed 's|1.0.||g')
          echo "Creating MEngZy base package with version: $MATCHZY_VERSION"
          dotnet publish -o package/addons/counterstrikesharp/plugins/MEngZy
          cp -r cfg package 
          cd package && zip -q -r ../MEngZy-$MATCHZY_VERSION.zip * && cd ..
    
          echo "Creating package with CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION for Linux"
          cd package/
          echo "Installing CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION"
          [ -e addons/counterstrikesharp ] && rm -rf addons/counterstrikesharp && echo "CounterStrikeSharp removed" || echo "old CounterStrikeSharp not found"
          curl -s https://api.github.com/repos/roflmuffin/CounterStrikeSharp/releases/tags/v$CSSHARP_VERSION |
              grep "/counterstrikesharp-with-runtime-build-$CSSHARP_VERSION-linux" |
              cut -d : -f 2,3 |
              tr -d \" |
              head -n 1 |
              wget -O cssharp-linux.zip -qi -
          unzip -o cssharp-linux.zip -d .
          rm cssharp-linux.zip
          cd ../

          dotnet publish -o package/addons/counterstrikesharp/plugins/MEngZy

          cd package && zip -q -r ../MEngZy-$MATCHZY_VERSION-with-cssharp-linux.zip * && cd ..

          rm -r package/*

          echo "Creating package with CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION for Windows"
          cp -r cfg package
          cd package/
          echo "Installing CounterStrikeSharp (CSSharp) v$CSSHARP_VERSION"
          [ -e addons/counterstrikesharp ] && rm -rf addons/counterstrikesharp && echo "CounterStrikeSharp removed" || echo "old CounterStrikeSharp not found"
          curl -s https://api.github.com/repos/roflmuffin/CounterStrikeSharp/releases/tags/v$CSSHARP_VERSION |
              grep "/counterstrikesharp-with-runtime-build-$CSSHARP_VERSION-windows" |
              cut -d : -f 2,3 |
              tr -d \" |
              head -n 1 |
              wget -O cssharp-windows.zip -qi -
          unzip -o cssharp-windows.zip -d .
          rm cssharp-windows.zip
          cd ../

          dotnet publish -o package/addons/counterstrikesharp/plugins/MEngZy

          cd package && zip -q -r ../MEngZy-$MATCHZY_VERSION-with-cssharp-windows.zip * && cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: MEngZy ${{ env.MATCHZY_VERSION }}
          tag_name: ${{ env.MATCHZY_VERSION }}
          body: |
            请查阅 [`CHANGELOG.md`](https://github.com/MEngYangX/MEngZy/blob/main/CHANGELOG.md) 以了解更新日志。

            安装:
            以下有3个文件:
            一个是 MEngZy-0.0.1.zip，其中只包含 MEngZy 插件文件。将其内容解压到服务器的 csgo/ 目录中。(前置条件：Metamod和CounterStrikeSharp应该已经安装)
            
            第二个是 MEngZy-0.0.1-with-cssharp-linux.zip，其中包含 MEngZy 插件文件以及 CounterStrikeSharp 文件（适用于 Linux），这样您就无需单独安装 CounterStrikeSharp。只需将其内容解压到服务器的 csgo/ 目录中。
            第三个是 MEngZy-0.0.1-with-cssharp-windows.zip，与上述相同，但适用于 Windows。
            (前置条件：Metamod 应已在服务器上安装，其余 CounterStrikeSharp 和 MEngZy 将在您解压内容时安装）（推荐首次安装使用 WITH CSSHARP 版本）
          draft: false
          prerelease: false
          files: |
            MEngZy-${{ env.MATCHZY_VERSION }}.zip
            MEngZy-${{ env.MATCHZY_VERSION }}-with-cssharp-linux.zip
            MEngZy-${{ env.MATCHZY_VERSION }}-with-cssharp-windows.zip
